[package]
name = "merkle_tree_proof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-rs = "0.2.3"
hex = "0.4.3"
